export const iplTeams = [
  {
    name: "Chennai Super Kings",
    shortName: "CSK",
    logo: "/images/csk.png",
    colorPrimary: "#0081E5",
    colorAccent: "#FDB913",
  },
  {
    name: "Delhi Capitals",
    shortName: "DC",
    logo: "/images/dc.png",
    colorPrimary: "#E41E26",
    colorAccent: "#004C93",
  },
  {
    name: "Gujarat Titans",
    shortName: "GT",
    logo: "/images/gt.png",
    colorPrimary: "#A8C5E5",
    colorAccent: "#1B2133",
  },
  {
    name: "Kolkata Knight Riders",
    shortName: "KKR",
    logo: "/images/kkr.png",
    colorPrimary: "#F2A71B",
    colorAccent: "#3A225D",
  },
  {
    name: "Lucknow Super Giants",
    shortName: "LSG",
    logo: "/images/lsg.png",
    colorPrimary: "#0055A4",
    colorAccent: "#A7D4FF",
  },
  {
    name: "Mumbai Indians",
    shortName: "MI",
    logo: "/images/mi.png",
    colorPrimary: "#D1B44E",
    colorAccent: "#006CB7",
  },
  {
    name: "Punjab Kings",
    shortName: "PBKS",
    logo: "/images/pk.png",
    colorPrimary: "#B3B3B3",
    colorAccent: "#DD1F2D",
  },
  {
    name: "Rajasthan Royals",
    shortName: "RR",
    logo: "/images/rr.png",
    colorPrimary: "#004B8C",
    colorAccent: "#EB1A8F",
  },
  {
    name: "Royal Challengers Bengaluru",
    shortName: "RCB",
    logo: "/images/rcb.png",
    colorPrimary: "#000000",
    colorAccent: "#D51A20",
  },
  {
    name: "Sunrisers Hyderabad",
    shortName: "SRH",
    logo: "/images/srh.png",
    colorPrimary: "#000000",
    colorAccent: "#F26522",
  },
];
